#!/bin/bash
nodeip=$(ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1 }')
mkdir ~/.docker/
cp /opt/docker-auth.json ~/.docker/config.json
docker run -d -e METADATA=$(azure-custom-data) -e CONSULHOST=$nodeip -e NODE=$HOSTNAME --name operator --restart always -v ~/.docker/:/root/.docker/ -v /opt/config/:/opt/config/ -v /var/run/docker.sock:/var/run/docker.sock plum/wake-operator:c60758244
