#!/bin/bash
nodeip=$(/sbin/ip route | awk '/default/ { print $3 }' | tr -d '\n')
mkdir ~/.docker/
cp /opt/docker-auth.json ~/.docker/config.json
docker run -d -e NODEIP=$nodeip -e NODENAME=$HOSTNAME --name operator --restart always -v ~/.docker/:/root/.docker/ -v /opt/config/:/opt/config/ -v /var/run/docker.sock:/var/run/docker.sock plum/wake-operator:latest
