#!/usr/bin/env ruby

require_relative '../share/wake/parser'
require_relative '../share/wake/cluster'

parser = OptsParser.parse do |opts|
  opts.banner = "Usage: wake nodes list [options]"

  opts.optional :c, :cluster, "The name of the cluster to list nodes from"
end

cluster = if parser[:cluster]
  WakeCluster.get(parser[:cluster])
else
  WakeCluster.default
end

json = cluster.consul.catalog.nodes

nodes   = json.map do |node|
  {
    name: node["Node"],
    ip: node["Address"]
  }
end

puts JSON.pretty_generate nodes
