#!/usr/bin/env ruby

require_relative '../share/wake/parser'

OptsParser.parse do |opts|
  opts.banner = "Usage: wake host-images <command>"

  opts.subcommand :create,        'wake-host-images-create'
  opts.subcommand :"set-default", 'wake-host-images-set-default'
end
