#!/usr/bin/env ruby

require 'bundler/setup'
require 'azure'
require_relative '../share/wake/parser'
require_relative '../share/wake/config'

parser = OptsParser.parse do |opts|
  opts.banner = "Usage: wake host launch [options]"

  opts.required :i, :image, "Specify the id of the image to be run on the host"
  opts.boolean  :v, :verbose,  "Run verbosely"
end

management_certificate_path = File.join(CONFIG_DIR, "azure", "wake.pfx")
unless File.exists?(management_certificate_path)
  publish_settings = File.join(CONFIG_DIR, "azure", "wake.publishsettings")
  unless File.exists?(publish_settings)
    panic!(
"""
Could not find azure publish settings in wake config directory.
Please add your publish settings to '#{publish_settings}'.

You can download the settings here: https://manage.windowsazure.com/publishsettings
"""
    )
  end

  #TODO create pfx file!
end

Azure.management_certificate = management_certificate_path
Azure.subscription_id = WakeConfig.get_or_ask_for("azure.subscription.id")

vm_management = Azure.vm_management

params = {
  vm_name: 'test',
  vm_user: 'ryan',
  image: parser[:image],
  password: '',
  location: 'East US'
}

options = {
  :private_key_file => '~/.ssh/id_rsa',
  :vm_size => 'Small',
}

vm_management.create_virtual_machine(params,options)
