#!/usr/bin/env ruby

require_relative '../share/wake/parser'
require_relative '../share/wake/root'
require_relative '../share/wake/json_file'
require_relative '../share/wake/run'
require_relative '../share/wake/config'
require 'erb'
require 'fileutils'
require 'tmpdir'

parser = OptsParser.parse do |opts|
  opts.banner = "Usage: wake seed [options]"

  opts.required :r, :revision, "The git revision to be packaged"
  opts.boolean  :v, :verbose,  "Run verbosely"
end

manifest = JSONFile.new("manifest.json")
platform = manifest.require("platform")
app      = manifest.require("app")
sha      = parser[:revision]

registry_host = WakeConfig.require("docker.registry.host")

platform = manifest.require("platform")
dockerfile_compile = File.join(WAKE_ROOT, "platforms", "wake", platform, "Dockerfile-compile.erb")

class Dockerfile
  attr_reader :path, :sha, :start

  def initialize(path:, sha:, start:, env: [])
    @path = path
    @sha = sha
    @start = start
    @env = env
  end

  def render
    ERB.new(File.read(path)).result(binding)
  end
end

processes = manifest.require("processes")

# get all the files git knows about
git_files = `git ls-files`.lines.map(&:chomp)

# get all the files in any submodule
path_regex = /\A\s*path = (\w+)\s*\z/

submodules = if File.exists?(".gitmodules")
  File.read(".gitmodules").lines.map(&:chomp)
    .grep(path_regex) { |l| l.match(path_regex)[1] }
else
  []
end

# merge the submodules and the regular files
submodules.each do |s|
  git_files.delete(s)
  Dir.chdir(s) do
    git_files.concat `git ls-files`.lines.map(&:chomp)
      .map { |l| File.join(s, l) }
  end
end

Dir.mktmpdir do |tmpdir|
  # p tmpdir

  # copy every file over to the same structure
  git_files.each do |f|
    nested_dir = File.join(tmpdir, File.dirname(f))
    FileUtils.mkdir_p(nested_dir)
    FileUtils.cp(f, nested_dir, preserve: true)
  end

  # go to the tmpdir
  Dir.chdir tmpdir

  processes.each do |process_name, process_info|
    start = process_info["start"]

    dockerfile = Dockerfile.new(
      path: dockerfile_compile,
      sha: sha,
      start: start
    )

    folder = ".processes/#{process_name}"
    FileUtils.mkdir_p(folder)
    dockerfile_local_path = "#{folder}/Dockerfile-compile"

    File.open(dockerfile_local_path, "w") do |f|
      f << dockerfile.render
    end

    File.open(".dockerignore", "w") do |f|
      f << ".git/*"
      f << ".processes/*"
    end

    name = if processes.length == 1 && app == process_name
             app
           else
             "#{app}-#{process_name}"
           end

    image_name = "wake-services/#{name}:#{sha}"

    puts "Building #{image_name}..."

    command = "docker build -t #{image_name} -f #{dockerfile_local_path} ."
    puts command
    run! command, parser[:verbose]

    # run! "docker tag #{image_name} #{registry_host}/#{image_name}", parser[:verbose]
    # run! "docker push #{registry_host}/#{image_name}", parser[:verbose]
  end
end
