#!/usr/bin/env ruby

require_relative '../share/wake/parser'

OptsParser.parse do |opts|
  opts.banner = "Usage: wake config <command>"

  opts.subcommand :get, 'wake-config-get'
  opts.subcommand :set, 'wake-config-set'
  opts.subcommand :del, 'wake-config-del'
end

