#!/usr/bin/env ruby

require_relative '../share/wake/parser'

OptsParser.parse do |opts|
  opts.banner = "Usage: wake container-imagess <command>"

  opts.subcommand :create, 'wake-container-images-create'
end
