#!/usr/bin/env ruby

require_relative '../share/wake/parser'
require_relative '../share/wake/cluster'

parser = OptsParser.parse do |opts|
  opts.banner = "Usage: wake env unset [options]"

  opts.optional :c, :cluster, "The name of the cluster to unset variables for"
  opts.required :a, :app,     "The name of the application to unset an ENV variable for"
  opts.required :n, :name,    "The name of the variable to unset"
end

cluster = if parser[:cluster]
  WakeCluster.get(parser[:cluster])
else
  WakeCluster.default
end

cluster.consul.env.unset(app: parser[:app], name: parser[:name])
