#!/usr/bin/env ruby

require_relative '../share/wake/parser'

OptsParser.parse do |opts|
  opts.banner = "Usage: wake hosts <command>"

  opts.subcommand :connect, 'wake-hosts-connect'
  opts.subcommand :create,  'wake-hosts-create'
  opts.subcommand :delete,  'wake-hosts-delete'
  opts.subcommand :run,     'wake-hosts-run'
  opts.subcommand :setup,   'wake-hosts-setup'
end

