#!/usr/bin/env ruby

require 'uri'
require_relative '../share/wake/parser'
require_relative '../share/wake/ssh_proxy'

OptsParser.parse do |opts|
  opts.banner = "Usage: wake containers remove [options]"

  opts.required :host, "Name of the host to remove the container from"
  opts.required :name, "Name of the contianer to remove"
end

cluster = if parser[:cluster]
  WakeCluster.get(parser[:cluster])
else
  WakeCluster.default
end

# TODO: add error checking for hosts exists

key = "_wakeful/hosts/#{parser[:host]}/apps/#{parser[:name]}"

command = cluster.consul.del key

puts JSON.pretty_generate({
  output: command.output
})
