#!/usr/bin/env ruby

require_relative '../share/wake/parser'
require_relative '../share/wake/run'
require_relative '../share/wake/config'


parser = OptsParser.parse do |opts|
  opts.banner = "Usage: wake seed [options]"

  opts.required :p, :platform, "Specify platform"
  opts.boolean  :v, :verbose,  "Run verbosely"
end

def remote_image_exists?(registry_host, image_name, verbose)
  _, err, exit_code = run "docker pull #{registry_host}/#{image_name}"

  if exit_code.success?
    true
  else
    if err.first.include?("not found")
      false
    else
      $stderr.puts "There was trouble talking with the remote docker repo."
      exit(1)
    end
  end
end

registry_host = WakeConfig.get_or_ask_for("docker.registry.host")
image_name = "wake-platforms/#{parser[:platform]}:latest"

unless remote_image_exists?(registry_host, image_name, parser[:verbose])
  run! "packer build -var 'platform=#{parser[:platform]}' templates/platform.json", parser[:verbose]

  run! "docker tag #{image_name} #{registry_host}/#{image_name}", parser[:verbose]
  run! "docker push #{registry_host}/#{image_name}", parser[:verbose]
end
