#!/usr/bin/env ruby

require 'uri'
require_relative '../share/wake/parser'
require_relative '../share/wake/cluster'
require_relative '../share/wake/azure/ssh_proxy'

parser = OptsParser.parse do |opts|
  opts.banner = "Usage: wake directory show [options]"

  opts.optional :c, :cluster, "The name of the cluster to find the node in"
end

cluster = if parser[:cluster]
  WakeCluster.get(parser[:cluster])
else
  WakeCluster.default
end

# TODO: add error checking for hosts exists

result = cluster.consul.directory.everything

puts JSON.pretty_generate result
