#!/usr/bin/env ruby

require_relative '../share/wake/parser'
require_relative '../share/wake/panic'
require_relative '../share/wake/root'
require_relative '../share/wake/config'
require_relative '../share/wake/run'


parser = OptsParser.parse do |opts|
  opts.banner = "Usage: wake cluster create [options]"

  opts.required :n, :name, "Specify name"
  opts.required :consul_image, "Specify consul image"
  opts.required :rsyslog_image, "Specify rsyslog image"
  opts.boolean  :v, :verbose,  "Run verbosely"
end

result = run "docker run -d -e 'CONSULJOIN=1.1.1.1' -e 'CONSULBOOTSTRAP=3' #{parser[:consul_image]} /sbin/my_init"

consul_cid = result[0][0]
consul_ip = JSON.parse(`docker inspect #{consul_cid}`)[0]["NetworkSettings"]["IPAddress"]

run "docker run -d -e 'CONSULJOIN=#{consul_ip}' -e 'CONSULBOOTSTRAP=3' #{parser[:consul_image]} /sbin/my_init"
run "docker run -d -e 'CONSULJOIN=#{consul_ip}' -e 'CONSULBOOTSTRAP=3' #{parser[:consul_image]} /sbin/my_init"
run "docker run -d -e 'CONSULJOIN=#{consul_ip}' #{parser[:rsyslog_image]} /sbin/my_init"
