#!/usr/bin/env ruby

require_relative '../share/wake/parser'
require_relative '../share/wake/config'

parser = OptsParser.parse do |opts|
  opts.banner = "Usage: wake config del [options]"

  opts.required :k, :key,   "The name of the configuration setting"
end

WakeConfig.delete(parser[:key])
