#!/usr/bin/env ruby

require_relative '../share/wake/parser'

OptsParser.parse do |opts|
  opts.banner = "Usage: wake host <command>"

  opts.subcommand :launch, 'wake-host-launch'
  opts.subcommand :terminate, 'wake-host-terminate'
end
