#!/usr/bin/env ruby

require 'uri'
require_relative '../share/wake/parser'
require_relative '../share/wake/cluster'
require_relative '../share/wake/azure/ssh_proxy'

parser = OptsParser.parse do |opts|
  opts.banner = "Usage: wake containers list [options]"

  opts.optional :c, :cluster, "The name of the cluster to find the node in"
  opts.required :d, :node,    "Name of the node to get container info about"
end

cluster = if parser[:cluster]
  WakeCluster.get(parser[:cluster])
else
  WakeCluster.default
end

# TODO: add error checking for hosts exists

key = "_wakeful/nodes/#{parser[:node]}/apps/"

pairs = cluster.consul.kv.get key, recurse: true

apps = pairs.map do |pair|
  service = JSON.parse(pair.value)

  {
    name:  pair.name,
    image: service["image"],
    tags:  service["tags"]
  }
end

node_command  = cluster.consul.catalog.node_info parser[:node]
node_json     = JSON.parse node_command.output
services      = node_json["Services"]

apps = apps.map do |app|
  app.merge registered: services.key?(app[:name])
end

puts JSON.pretty_generate(apps)
