#!/usr/bin/env ruby

require_relative '../share/wake/parser'
require_relative '../share/wake/cluster'
require_relative '../share/wake/manifest'

parser = OptsParser.parse do |opts|
  opts.banner = "Usage: wake env unset [options]"

  opts.optional :c, :cluster, "The name of the cluster to unset variables for"
  opts.optional :a, :app,     "The name of the application to unset an ENV variable for"
  opts.required :n, :name,    "The name of the variable to unset"
end

cluster = if parser[:cluster]
  WakeCluster.get(parser[:cluster])
else
  WakeCluster.default
end

if parser[:app].nil? && !Wake::Manifest.exists?
  panic! "Must either provide --app or have a valid manifest.json in the current directory"
end

parser[:app] ||= Wake::Manifest.new.app

cluster.consul.env.unset(app: parser[:app], name: parser[:name])
